### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by fokoid** [baruchel/vim-notebook#1]
I would like to fork this project to hack on it a bit. Since there's no licence file in the repo I first wanted to ask for clarification of the licensing. Are you keen to keep it unlicensed or would you consider using a permissive open source license (e.g. MIT license)?

**Comment by baruchel** [comment]
Hi, maybe I forgot to put a license file. However, most of my work is released under the MIT license, which is the case for this project. Please, go ahead! Regards.
